language: node_js

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - node_modules/.bin/newman run testcollections/SPA-SingleAppointment.postman_collection.json